name: Waka Readme

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme With WakaTime Metrics
    runs-on: ubuntu-latest

    steps:
      - uses: durgaaisolutions/durgaai-waka-stats@main  # 👈 This is where you use the action
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "True"
          PUSH_BRANCH_NAME: "main"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_COMMIT: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_SHORT_INFO: "True"
          SYMBOL_VERSION: 1
          COMMIT_USERNAME: "readme-bot"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          COMMIT_MESSAGE: "🕒 Updated with Dev Metrics"
          SECTION_NAME: "waka"
